### ISSUE TITLE
A question about the dataset of RNA secondary structure

### ISSUE THREAD

**Issue by fuxuliu** [yikunpku/RNA-MSM#2]
Hi, thanks for sharing this great work.
As for the dataset used for RNA secondary structure  was mentioned in the paper: "405 RNAs for TR1, 40 RNAs for VL1 and 39 RNAs for TS1, ..., We combined TS1 and TS2 to make the final independent test set with 70 RNAs (TS)".
I downloaded the data set for RNA secondary structure from SPOT-RNA or SPOT-RNA2, but the number of samples did not match the number mentioned in RNA-MSM. So, I was wondering, did you update the data set or did I download it by mistake. Would you mind sharing this new data or the download link?
Thanks.

**Comment by meilanglang** [comment]
The data set of RNA secondary structure is different from the SPOT-RNA or SPOT-RNA2, it is a new data set.

**Comment by yikunpku** [comment]
> Hi, thanks for sharing this great work. As for the dataset used for RNA secondary structure was mentioned in the paper: "405 RNAs for TR1, 40 RNAs for VL1 and 39 RNAs for TS1, ..., We combined TS1 and TS2 to make the final independent test set with 70 RNAs (TS)". I downloaded the data set for RNA secondary structure from SPOT-RNA or SPOT-RNA2, but the number of samples did not match the number mentioned in RNA-MSM. So, I was wondering, did you update the data set or did I download it by mistake. Would you mind sharing this new data or the download link? Thanks.

We have update the training, validation, and testing datasets used for our downstream tasks, they are currently available to the public and can be downloaded.  See the **README-Data Preparation-Downstream Task Data** for download link.

**Comment by fuxuliu** [comment]
I got it, thanks so much.
