### ISSUE TITLE
web server

### ISSUE THREAD

**Issue by fiting-all** [yikunpku/RNA-MSM#4]
When I submit tasks using RNA-MSM web server, the following issue always appear.
![web](https://user-images.githubusercontent.com/106303234/236614104-5d021ae6-8236-43f5-9a04-5119fe05f7a8.png)

**Comment by yikunpku** [comment]
> When I submit tasks using RNA-MSM web server, the following issue always appear. ![web](https://user-images.githubusercontent.com/106303234/236614104-5d021ae6-8236-43f5-9a04-5119fe05f7a8.png)

Hello, I just checked our website and submitted a simple test task. The website works normally without the state of 414. Could you try to submit it again?

**Comment by fiting-all** [comment]
Okay, the problem has been resolved. Thank you.
