### ISSUE TITLE
Could not find fair-msm

### ISSUE THREAD

**Issue by Binyun-Z** [yikunpku/RNA-MSM#7]
ERROR: Could not find a version that satisfies the requirement fair-msm
ERROR: No matching distribution found for fair-msm

**Comment by llk15** [comment]
same problem, could not find fair-msm==1.0.2

**Comment by saldanB** [comment]
Same for me. Probably wrong dist name?

**Comment by yikunpku** [comment]
Hi there, my apologies for the delay in getting back to you. I have made some updates to the environment.yaml file and this version should now match the one in my coding environment. Please use this new setup going forward!
