### ISSUE TITLE
ModuleNotFoundError: No module named 'msm.version'

### ISSUE THREAD

**Issue by JinwnK** [yikunpku/RNA-MSM#9]
Hello, There is an error when I run the command:
```
$ conda activate rnamsm
(rnamsm) [kjw@master RNA-MSM]$ python RNA_MSM_Inference.py \
> data.root_path=/public/work/jinwen/4Gdb_test/RNA-MSM/test \
> data.MSA_path=/public/work/jinwen/4Gdb_test/RNA-MSM/test/results \
> data.model_path=/public/work/jinwen/4Gdb_test/RNA-MSM/test/pretrained \
> data.MSA_list=/public/work/jinwen/4Gdb_test/RNA-MSM/test/rna_id.txt
Traceback (most recent call last):
  File "RNA_MSM_Inference.py", line 5, in <module>
    from utils.tokenization import Vocab
  File "/public/work/jinwen/software/RNA-MSM/utils/tokenization.py", line 6, in <module>
    import msm
  File "/public/work/jinwen/software/RNA-MSM/msm/__init__.py", line 6, in <module>
    from .version import version as __version__  # noqa
ModuleNotFoundError: No module named 'msm.version'
```

**Comment by Yanxu-Zhu** [comment]
the same with me.Did you fix it？

**Comment by JinwnK** [comment]
> the same with me.Did you fix it？

I haven't fixed it yet.

**Comment by Yanxu-Zhu** [comment]
Do you have any good rna models to recommend?

**Comment by JinwnK** [comment]
> Do you have any good rna models to recommend?

I'm trying RNA-FM, RNAErnie.

**Comment by Yanxu-Zhu** [comment]
Thanks for your recommendation！

**Comment by LiuJeremy** [comment]
In the __init__.py file in the msm folder, you can add some annotations


# from .version import version as __version__  # noqa

from .data import Alphabet, BatchConverter, FastaBatchedDataset  # noqa
from .model import ProteinBertModel, MSATransformer  # noqa
# from . import pretrained  # noqa

**Comment by LiuJeremy** [comment]
In the init.py file in the msm folder, you can add some annotations.
```
\# from .version import version as __version__  # noqa
from .data import Alphabet, BatchConverter, FastaBatchedDataset  # noqa
from .model import ProteinBertModel, MSATransformer  # noqa
\# from . import pretrained  # noqa
```

**Comment by JinwnK** [comment]
> In the init.py file in the msm folder, you can add some annotations.
> 
> ```
> \# from .version import version as __version__  # noqa
> from .data import Alphabet, BatchConverter, FastaBatchedDataset  # noqa
> from .model import ProteinBertModel, MSATransformer  # noqa
> \# from . import pretrained  # noqa
> ```

Thank you , it works!
